### PR TITLE
Add needletail.rs fqcnt example

### PR DESCRIPTION
**Pull request by bovee**
Another example implementation in Rust using an alternate FASTX parsing library.

### CODE REVIEW

**Comment by bovee** [comment]
As an alternate Rust implementation to the one in rust-bio, this is using the low-copy FASTX reader in [needletail](https://crates.io/crates/needletail). The parse code is fairly similar to kseq, but it uses an extra "trick" in parsing the quality by assuming it's the same length as the sequence (which prevents an extra `memchr`).

Benchmarking using `hyperfine` and the example code from #5 on my laptop:

## M_abscessus_HiSeq.fq

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./fqcnt_c1_kseq /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq` | 841.9 ± 15.1 | 825.6 | 866.9 | 1.77 ± 0.07 |
| `./bin/fqcnt_rustbio /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq` | 1700.2 ± 15.7 | 1664.6 | 1715.7 | 3.57 ± 0.12 |
| `./bin/fqcnt_needletail /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq` | 475.6 ± 15.9 | 463.4 | 516.0 | 1.00 |
| `./fqcnt_go1 /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq` | 1715.8 ± 19.9 | 1693.8 | 1755.4 | 3.61 ± 0.13 |
| `./fqcnt_py6x_pyfx.py /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq` | 5177.3 ± 80.6 | 5085.8 | 5336.4 | 10.88 ± 0.40 |
| `./fqcnt_py7x_pysam.py /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq` | 8505.0 ± 171.1 | 8208.6 | 8774.3 | 17.88 ± 0.70 |

## M_abscessus_HiSeq.fq.gz

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `./fqcnt_c1_kseq /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq.gz` | 7.610 ± 0.042 | 7.560 | 7.677 | 1.05 ± 0.01 |
| `./bin/fqcnt_rustbio /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq.gz` | 7.965 ± 0.159 | 7.795 | 8.262 | 1.10 ± 0.03 |
| `./bin/fqcnt_needletail /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq.gz` | 7.241 ± 0.080 | 7.139 | 7.443 | 1.00 |
| `./fqcnt_go1 /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq.gz` | 14.059 ± 0.048 | 13.935 | 14.099 | 1.94 ± 0.02 |
| `./fqcnt_py6x_pyfx.py /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq.gz` | 12.476 ± 0.205 | 12.184 | 12.803 | 1.72 ± 0.03 |
| `./fqcnt_py7x_pysam.py /home/roderick/Downloads/biofast-data-v1/M_abscessus_HiSeq.fq.gz` | 13.623 ± 0.170 | 13.335 | 13.864 | 1.88 ± 0.03 |

**Comment by lh3** [comment]
I will pull your changes first. I will update numbers later. Thanks!

**Comment by lh3** [comment]
Does needletail only work with 4-line fastq files? Or does it seamlessly work with multi-line fasta/fastq like kseq.h?

**Comment by bovee** [comment]
Thanks! And thanks for putting this all together!

needletail does work seamlessly with multiline FASTAs. FASTQs are a little more complicated: it will parse the more common ones (where the sequence and quality are both wrapped at the same length), but it doesn't strip out newlines from inside the sequence/quality records by default.

**Comment by lh3** [comment]
Thanks. In the table, I said needletail works with "mostly" 4-line fastq in that you have additional restrictions on multi-line fastq and that users need to strip off newlines by themselves.

It is totally fine for a parser to work with 4-line fastq only. I haven't seen a multi-line fastq in a long while. The comment is only for the benchmark purpose.

**Pull request merged**
